pipeline {
    agent { lable 'master' }
    stages{
        stage ('build') {
            steps {
                sh 'sleep 5'
            }
        }
        stage ('deploy') {
            steps {
                sh 'sleep 5'
            }
        }
        stage ('test') {
            steps {
                sh 'sleep 5'
            }
        }
    }
}